eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.7:8761/eureka/
server:
  port: 8763

spring:
  application:
    name: eshop-price-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://172.17.0.5:3306/eshop
    username: eshop
    password: eshop


